### ISSUE TITLE
Impossible to ignore nested folders

### ISSUE THREAD

**Issue by tommysanterre** [old-reliable/steamroller#13]
I have a folder that contains generated files
lib/sxv/src/proto/sxv_common_pb.erl
lib/sxv/src/proto/many-others_pb.erl
lib/sxv/src/proto/many-others_pb.hrl

I need to be able to exclude a folder or a pattern in the file name. Otherwise my build fails on the steamroller --check because the generated file is not formatted properly.

Wildcard is used to find files but it does not support ignoring a pattern
https://erlang.org/doc/man/filelib.html#wildcard-1

Also is it expected that we don't use the provided pattern here?
https://github.com/old-reliable/steamroller/blob/ee7f099468dc37aed4104f119a215a43243ad6e3/src/steamroller_prv.erl#L116

**Comment by tommysanterre** [comment]
I worked around the issue by running the check before every other steps on my ci,

**Comment by dtip** [comment]
Glad you have a workaround!

Short of forking wildcard I'm not sure there's much we can do here. Open to ideas. I would suggest that instead of excluding a directory you instead explicitly include only the directories you want to format. I appreciate that may be impractical on large projects!

> Also is it expected that we don't use the provided pattern here?

Yep. Formatting a single directory is basically a hack which I use occasionally during development. The canonical way to run the formatter is `rebar3 steamroll` from the project root.

**Comment by tommysanterre** [comment]
Instead of using wildcards regular expression could be used.
They're more flexible, but more complex. This beautiful regex excludes the files I don't want.
```
^(?:\.\/rebar\.config|\.\/(?!_build).*\/(?:src|test).*(?!pb)\.(?:[he]rl|app\.src))$
```
Or maybe allow a custom filter function that has the same signature as wildcard.
Maybe allow both options and use whatever the user provided.

**Comment by dtip** [comment]
You're welcome to open a PR for this :)

**Comment by tommysanterre** [comment]
I won't, if I'm the only one affected by this you could close the issue.

**Comment by dtip** [comment]
Ok!
