### ISSUE TITLE
Error - "Multiple app files found in one app dir"

### ISSUE THREAD

**Issue by szTheory** [old-reliable/steamroller#4]
Got an error while running `rebar3 steamroll` on this project https://github.com/pgourlain/vscode_erlang

```
vscode_erlang on master
➜ rebar3 steamroll                                            
===> Multiple app files found in one app dir: /Users/blue/projects/vscode_erlang/apps/erlangbridge/src/erlangbridge.app.src and /Users/blue/projects/vscode_erlang/apps/erlangbridge/src/vscode_lsp.app.src
```

Also this is separate, but is there a way to use it without adding to `rebar.config`? If it's available to use on any erlang file from the command line I think it would be easy to integrate with VS Code as a formatter.

**Comment by dtip** [comment]
I'm afraid this isn't a steamroller issue. That project has two .app.src files which means rebar3 refuses to compile it:
```
λ vscode_erlang master✓ » rebar3 compile
===> Multiple app files found in one app dir: /home/dtip/erlang/vscode_erlang/apps/erlangbridge/src/erlangbridge.app.src and /home/dtip/erlang/vscode_erlang/apps/erlangbridge/src/vscode_lsp.app.src
```

There's a rebar3 version included with the project so I tried using that one too but got the same error!

One of the .app.src files needs to be deleted to make the project OTP-compliant, but I'm not sure which one.

-----

To answer your other question, would adding steamroller to your global rebar3 config do what you want?

I wouldn't recommend it personally because some Erlang projects you work on may not use steamroller. I think it should be added to the rebar.config of each project individually.

Why would this make it easier to integrate with VS Code? You can run the formatter from the command line using `rebar3 steamroll`. It seems like you should be able to catch the case where steamroller isn't found and perform to autoformatting in that case. Admittedly I have no knowledge of what it takes to build a VS Code plugin ;)

**Comment by szTheory** [comment]
Thanks. It sounds like this project is closely tied to rebar3 being a dep, which is great for those projects. What I'm looking for is the ability to format Erlang file on save it being tied to rebar3. For example if just noodling around in a random .erl file saved to my desktop, or I want to format only a single file from an existing rebar project, or an .erl file in an Elixir project, etc. I get that right now with Elixir and Javascript and it's incredibly convenient.

**Comment by dtip** [comment]
How would you do it with Elixir?

**Comment by szTheory** [comment]
If I save an open .ex file in VS Code it formats the code with `mix format` (requires Elixir >= 1.6 installed). I'm using the `vscode-elixir` extension, which performs that action here https://github.com/fr1zle/vscode-elixir/blob/ccf9457ebed29b80f8ac4f5e855cc9596d1546f6/src/elixirFormatter.ts#L22. I'd be willing to build a new extension to do this and/or contribute to existing Erlang extensions on the VS Code marketplace.

**Comment by dtip** [comment]
If you're using `mix format` for Elixir, what's wrong with using `rebar3 steamroll` for Erlang? You're using a build tool either way. As long as rebar3 and steamroller are installed globally I think this should be equivalent.

**Comment by dtip** [comment]
I think the problem is that if you run `rebar3 steamroll` from within vscode_erlang then rebar3 will try to compile the code first. That will fail so the formatting will fail too. I think `mix format` has the same behaviour.

**Comment by szTheory** [comment]
I'm probably missing something obvious, but if I run `rebar3 steamroll` outside of a project dir with the steamroll dep set up in rebar config, I get this error. Thanks for your patience.

```
➜ rebar3 steamroll
===> Command steamroll not found
```

**Comment by dtip** [comment]
I think that means you haven't added steamroller to your global rebar3 config. See https://www.rebar3.org/docs/using-available-plugins

Your global rebar3 config should be at `~/.config/rebar3/rebar.config`

There needs to be a line which says `{plugins, [steamroller]}.`

You should then be able to run `rebar3 steamroller` in any directory!

**Comment by szTheory** [comment]
Thanks it worked! I was able to format an arbitrary file with `rebar3 steamroll -f erltest.erl` without event being in a rebar3 project directory.

**Comment by dtip** [comment]
Great stuff :)

@szTheory please get in touch if you're able to get steamroller to integrate with VS Code. Would be great to have instructions on the README!
